---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: data/tr/homepage.yml
  label: Homepage (tr)
- type: document
  path: data/fr/homepage.yml
  label: Homepage (fr)
- type: document
  path: data/tr/testimonial.yml
  label: Testimonials (tr)
- type: heading
  label: Blog Post
- type: directory
  path: content/turkish/blog
  label: Post (tr)
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content/french/blog
  label: Post (fr)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Products
- type: directory
  path: content/turkish/products
  label: Product (tr)
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/french/products
  label: Products (fr)
  create: documents
  match: "**/*"
  templates:
  - product
- type: heading
  label: Contact
- type: document
  path: content/turkish/contact/_index.md
  label: Contact (tr)
- type: document
  path: content/french/contact/_index.md
  label: Contact (fr)
- type: heading
  label: All Pages
- type: directory
  path: content/turkish
  label: All Page (tr)
  create: all
  match: "**/*"
- type: directory
  path: content/french
  label: All Page (fr)
  create: all
  match: "**/*"
- type: heading
  label: Translations
- type: directory
  path: i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
